# Generated by Django 3.2.7 on 2021-10-12 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblehelp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=500)),
                ('cite', models.CharField(max_length=100)),
                ('scripture_text', models.CharField(max_length=1000)),
                ('personal_goal', models.CharField(blank=True, max_length=1000)),
                ('setter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
